import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto px-4 py-5 flex justify-center items-center gap-4">
          <Link
            href={"/"}
            className="py-2 px-3 rounded-md bg-blue-400 text-white"
          >
            Home
          </Link>
          <Link
            href={"/allusers"}
            className="py-2 px-3 rounded-md bg-blue-400 text-white"
          >
            Allusers
          </Link>
        </div>
        {children}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
